### ISSUE TITLE
start version control with git

### ISSUE THREAD

**Issue by carolclark** [carolclark/DevOps#22]
use git version control

*we have a GitHub wiki for DevOps, but it is not under version control*

- [ ] #21 basic git workflow
- [ ] #19 local clone of DevOps
- [ ] #20 local clone of DevOps wiki
